### ISSUE TITLE
[Shaqodoon] Beta environment is down

### ISSUE THREAD

**Issue by raulbobletec** [sebiboga/automation_internship_2021#9]
**ENVIRONMENT:** Beta
  URL: http://zimbor.go.ro/
  browser: Chrome

**Severity:** Critical

**STEPS TO REPRODUCE:**
  1) Open URL in browser
  2) Check results

**EXPECTED RESULTS:**
  The page should load without errors

**ACTUAL RESULTS:**
  The page is not loading
  The beta environment is down.

**Comment by sebiboga** [comment]
@raulbobletec I think I fixed the issue. please RETEST

**Comment by raulbobletec** [comment]
Retested on beta environment
This issue has been fixed
Closing the bug.
